name: Python Project CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas pytest

    - name: Run tests with pytest
      run: |
        pytest
      working-directory: ./my_project

    - name: Run the actual pipeline
      run: python my_project/main.py

    - name: Run the query service
      run: python my_project/query_service.py

    - name: Run database manager
      run: python my_project/database_manager.py

    - name: Run LLM Adaptor
      run: python my_project/llm_adaptor.py
